### ISSUE TITLE
Issues in Index.py Imports & Readme info

### ISSUE THREAD

**Issue by Insider4444** [jayant-0000/maze-master#2]
# Issue: Missing Maze Module and Inadequate README Information

## Description

The current project is facing two main issues:
1. The required module called `maze` is missing from the project structure and is located in another folder.
2. The README file does not provide sufficient information for users to understand how to use the project effectively.

### Missing Maze Module
The module named `maze` is not present within the project directory. It seems to be located in another folder or directory. This makes it difficult for users to run the project successfully as it relies on this module for functionality.

### Inadequate README Information
The README file provided with the project lacks comprehensive details on how to install, configure, and use the project. Users may find it challenging to understand the purpose of the project, its features, and how to get started with it.

## Proposed Solution

I have addressed these issues by:
1. Adding the missing `maze` module to the project directory.
2. Enhancing the README file to include detailed instructions on installation, configuration, and usage of the project.

## Pull Request

I have submitted a pull request that resolves these issues. You can review the changes made in the [Pull Request](https://github.com/jayant-0000/maze-master/pull/1) to see the modifications made to address the missing module and improve the README file.

## Highlighted Code Change

In the `index.py` file, **line 4** to include `maze` module.

```python
import maze  # <- This line was added to import the 'maze' module
```
but missing error while running (fixed this)

**Comment by jayant-0000** [comment]
Issue resolved @Insider4444
